### ISSUE TITLE
fails to build in openshift developer preview

### ISSUE THREAD

**Issue by tommybutler** [openshift/dancer-ex#49]
Log excerpt:
Pushing image 172.30.47.227:5000/dancertest2/dancer-mysql-example:latest ...
error: build error: Failed to push image: unauthorized: authentication required

**Comment by bparees** [comment]
Was this your first build attempt?

**Comment by bparees** [comment]
(if you run another build, do you hit the same issue?)

**Comment by bparees** [comment]
(This is almost certainly either https://bugzilla.redhat.com/show_bug.cgi?id=1374091 or https://bugzilla.redhat.com/show_bug.cgi?id=1333030)

**Comment by tommybutler** [comment]
This happened two times in a row.  Should I try for a third time?

**Comment by bparees** [comment]
to be clear, are you creating a new project each time? or you're just running start-build a second time?

**Comment by tommybutler** [comment]
I created a new project each time.

**Comment by bparees** [comment]
don't do that.  just run the build a second time.

**Comment by tommybutler** [comment]
I also tried and after a 3-4 minute build process it succeeds, pushes 5 layers and says 'end of log'.  Then in the overview portion of the openshift console it shows that the the main dancer pod is live but then eventually warns "this pod is failing too frequently and has to wait to start again".  I think it's failing due to the dependency on the mysql database pod which always shows as failed.

**Comment by bparees** [comment]
yeah so that's going to be a different issue and we can debug it if you like, but your push image failure is due to the timing window described in the two bugs I referenced above.

to debug the pod failure to start, i'll need to see exact recreate steps from you, and/or you can look at the pod log to see if it is reporting the reason it's failing.  you can use "oc logs <podname> -p" to get the logs from the previous container run.

**Comment by tommybutler** [comment]
I was able to force the database pod to deploy, and after it deployed, the dancer pod started running again.

```

$ oc get pods
NAME                           READY     STATUS      RESTARTS   AGE
dancer-mysql-example-1-5awmn   1/1       Running     1          3m
dancer-mysql-example-1-build   0/1       Error       0          41m
dancer-mysql-example-2-build   0/1       Completed   0          8m
database-1-deploy              0/1       Error       0          42m
database-2-3zdro               1/1       Running     0          3m

$ oc logs -f database-1-deploy
error: couldn't get deployment database-1: replicationcontrollers "database-1" not found


```

**Comment by bparees** [comment]
what's database-2?

**Comment by tommybutler** [comment]
that's the one I forced to deploy manually...

**Comment by tommybutler** [comment]
I'm in #dfwpm channel in irc.perl.org if you want to chat.  I'll get you my api token for oc and you can look at the logs.  I am admittedly not an expert.  I'm trying to prepare a presentation on openshift for my perl mongers programmer user group.

**Comment by bparees** [comment]
so just to summarize this:  the original issue w/ the build push failing is the aforementioned timing window noted in the bugzilla log (running a build immediately after creating a new project causes this).  running a second build should resolve it, if you hit it.

the database deployment failure is a bit more confusing but at least in my investigation a deployment failed because
1) the infrastructure took forever binding a persistent volume to the DB pod
2) the infrastructure then took forever starting up the container once the volume was bound

which ultimately resulted in a DB deployment failure.

in the meantime, the dancer pod deployment failed because it requires the DB to be available to pass its readiness check, and since the DB never deployed, the dancer deploy could never succeed.

Closing this since none of it is dancer-ex related, but i'll talk to the ops team about the infrastructure problems.
