### ISSUE TITLE
Incompatible with ubi8 perl images

### ISSUE THREAD

**Issue by yselkowitz** [openshift/dancer-ex#78]
Two issues occur attempting to use the dancer template with perl:5.26-el8:

1.  Only the very latest version of DBD::mysql will build with libmariadb client:  https://github.com/multi-arch/dancer-ex/commit/f3bb206873bf363cdfb90e60a64b3e7ef5162c6c

2. While RHSCL (RHEL 7) perl images included mod_perl, UBI 8 perl images use fcgi.  The build completes, but deploying the pod fails:
```
AH00526: Syntax error on line 3 of /opt/app-root/etc/httpd.d/dancer.conf:
Invalid command 'PerlResponseHandler', perhaps misspelled or defined by a module not included in the server configuration
```
Somehow, cfg/dancer.conf needs to be made compatible with fcgi as well, without breaking compatibility with mod_perl when built with RHEL7/RHSCL perl.

These issues now block https://github.com/openshift/cluster-samples-operator/pull/320

cc: @hhorak

**Comment by hhorak** [comment]
@ppisar are you able to take a look at this, please? If it's not possible to have one code-base for both, we can have a branch for fcgi and reference that branch from the imagestreams.

**Comment by hhorak** [comment]
@pkubatrh FYI, please, try to monitor this during my PTO.

**Comment by ppisar** [comment]
You should use PSGI interface provided by the perl image <https://github.com/sclorg/s2i-perl-container/tree/master/5.26#environment-variables> instead or fiddling with httpd configuration (cfg/dancer.conf). Either move ./bin/app.psgi file to / or set PSGI_FILE environment variable to ./bin/app.psgi. It should work with both mod_http and mod_fcgid. See <https://github.com/sclorg/s2i-perl-container/tree/master/5.26/test/psgi> test. It's exactly the same test as in the RHEL-8 image.

Otherwise your are on you own and must manually configure httpd mod_fcgid to execute your./bin/app.psgi FCGI server. Not that it would be impossible to support both mod_perl and mod_fcgid in one dance-ex code, but it's significantly different.

Another option is to wrap to PSGI application into CGI and run that through mod_cgid. But it's terrible from point of view a performance.

**Comment by yselkowitz** [comment]
This isn't so much about what I should do, but about this sample and template which deploys it, and getting them to work out of the box with perl:5.26-ubi8.  I tried to implement your suggestion in this repo, resulting in https://github.com/multi-arch/dancer-ex/commit/20ee233e6db4e18b919218739fb7c287eedd37bf.  This builds and seems to run fine with both RHSCL/mod_perl and UBI8/mod_fcgid builder images with s2i, but when I try this in OpenShift, I get an error:

```
[Sun Sep 06 17:28:04.722760 2020] [fcgid:warn] [pid 18:tid 281472258011088] [client 10.131.0.1:52618] mod_fcgid: 150 environment variables dropped; increase INITENV_CNT in fcgid_pm.h from 64 to at least 214
Can't locate Plack/Runner.pm in @INC (you may need to install the Plack::Runner module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /opt/app-root/src/extlib/bin/plackup line 3.
BEGIN failed--compilation aborted at /opt/app-root/src/extlib/bin/plackup line 3.
[Sun Sep 06 17:28:04.733448 2020] [fcgid:warn] [pid 18:tid 281472258011088] (104)Connection reset by peer: [client 10.131.0.1:52618] mod_fcgid: error reading data from FastCGI server
[Sun Sep 06 17:28:04.733551 2020] [core:error] [pid 18:tid 281472258011088] [client 10.131.0.1:52618] End of script output before headers: health
```

**Comment by ppisar** [comment]
I'm glad to hear your application works now with the mod_fcgid-based s2i image.

Regarding the mod_fcgid warning, that's caused by a hard-coded limit of a number of the environment variables that mod_fcgid can pass to an FCGI application. It's 64 now and it seems that the silly idea of OpenShift to store a configuration into the environment rather than to a file system triggers it.

What do you think that a reasonable number of the variables that OpenShift needs is? I opened a future request to mod_fcgi package of RHEL 8 to increase the limit <https://bugzilla.redhat.com/show_bug.cgi?id=1876525>.

I believe that the current limit crops some variables from the environment of the perl process, and one of them is a path to the installed Perl modules in the assembly phase of the image and that causes the error about missing Plack/Runner.pm.

We already had a similar issue with a length of the variables <https://bugzilla.redhat.com/show_bug.cgi?id=1651310>.

If you replace the app.psgi content with:

~~~~
#!/usr/bin/perl
use Data::Dumper;
warn Data::Dumper::Dumper(\%ENV);
~~~~

and fetches an HTTP document from the running image, you should see in the image error log what variables got into the environment. I guess that PERL5LIB variable will be missing from there. Unfortunately I cannot test it, because I have no account in any OpenShift cluster.

**Comment by yselkowitz** [comment]
Thanks, that helped.  Running `oc debug dc/dancer-mysql-example` showed that the environment was littered with variables from all the different templates I had tried running in that OpenShift project, which is where the 200+ number came from.  Trying again in a new project with the aforementioned patches succeeds, but with your Data::Dumper command added for debugging, it shows 57 variables.  So in a clean project it does work as expected, but it's tight, so probably best if the hardcoded limit is raised to make this more future-proof.

I'll go ahead and proceed with a PR.

/cc @gabemontero
