### ISSUE TITLE
Pod breaks with manual addition of ConfigMap

### ISSUE THREAD

**Issue by elfner** [openshift/dancer-ex#80]
Hi I'm using the base template from this project (dancer.json) on Openshift 4.5, and when I add a ConfigMap, instead of just creating a new pod with the new environment variables, it the new pod fails with this error:

     $ oc logs -f dancer1-7cc875b4b6-k6kkn
     Sat Nov 21 17:46:07.425660 2020 so:warn pid 1 AH01574: module perl_module is already loaded, skipping
     AH00526: Syntax error on line 46 of /opt/app-root/etc/httpd.d/env.conf:
     PerlPassEnv takes one argument, PerlPassEnv

The ConfigMap file itself is trivial:

     $ cat filterPatterns 
     pattern1=foo
     pattern2=bar

Appreciate any tips or insight for doing this successfully - thanks.

**Comment by bparees** [comment]
please share the deploymentconfig yaml so we can understand how you've added the configmap to the deployment.

**Comment by elfner** [comment]
Attached is the deployment config yaml and a couple screen shots.
The configmap was created via:

    oc create configmap log-filters --from-file=filterPatterns

with the simple data:

    pattern1=foo
    pattern2=bar

And it was added to the deployment config via the Openshift GUI.

Thanks!
[deploymentconfig-dancer-example.yaml.txt](https://github.com/sclorg/dancer-ex/files/5619269/deploymentconfig-dancer-example.yaml.txt)
![new-pod-log](https://user-images.githubusercontent.com/9096655/100676936-24daeb00-3327-11eb-8f34-9b3ce74ae587.png)
![openshift-gui-deployment-config](https://user-images.githubusercontent.com/9096655/100676939-25738180-3327-11eb-89f7-edaf3c13e197.png)

**Comment by bparees** [comment]
hm.  It seems like something about your added env vars are tripping up this logic which adds all the env vars to the apache environment:

https://github.com/sclorg/s2i-perl-container/blob/master/5.30/s2i/bin/run#L14

resulting in a bad env.conf being generated.

but i can't see why that would be the case.

I think it's possible you didn't create the configmap as you intended:

1) please show the current configmap yaml
2) try creating the configmap using --from-env-file instead of --from-file, because i think that will get you the configmap you intend.

**Comment by elfner** [comment]
Hi Ben,

That was it - if I create the configmap in the GUI or by specifying --from-env-file instead of --from-file in the CLI, it works.
Thanks so much!

**Comment by bparees** [comment]
glad i could help!
